version: "3.9"
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "4000:4000"
  ui:
    build: ./react-ui
    volumes:
      - ./react-ui:/app
      - ./vue-ui (depricated)
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider=value
